version: '3.3'
services:
  db: 
    container_name: lp_mysql
    env_file: 
      - .env
    environment: 
      MYSQL_DATABASE: "${WORDPRESS_DB_NAME}"
      MYSQL_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${WORDPRESS_DB_USER}"
      MYSQL_USER: "${WORDPRESS_DB_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    image: "mysql:5.7"
    ports: 
      - "3306:3306"
    restart: always
    volumes: 
      - "db_data:/var/lib/mysql"
      - "./mysql:/docker-entrypoint-initdb.d"
    networks:
      - lp_net

  wordpress: 
      image: zionmaori/liveperson_wp:latest
      container_name: wp_lp
      env_file: 
        - .env
      environment: 
        WORDPRESS_CONFIG_EXTRA: |
            define('WP_HOME', '$WP_HOME');
            define('WP_SITEURL', '$WP_SITEURL');
            define('FS_METHOD', 'direct');
            set_time_limit(600);
        WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
        WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
        WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
        WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
        WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX}"
      ports: 
        - "80:80"
      restart: always
      volumes: 
        - "./wordpress:/var/www/html/"
      networks:
        - lp_net
networks:
  lp_net:
    driver: "bridge"
volumes:
  db_data: {}
