name: Docker Image CI for dev env

on:
  push:
    branches: [ dev ]
  pull_request_target:
    branches: [ dev ]
 
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      run: 
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      env:
        $DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        $DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}


  
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date 
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    
    - name: Build  the Docker image
      run: docker build ./wordpress --file Dockerfile --tag liveperson_wp:${{ steps.date.outputs.date }}
      
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
