name: Docker Image CI for dev env

on:
  pull_request_target:
    types:
      - opened
    branches: [ dev ]
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date 
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    
    - name: Build  the Docker image
      run: docker build ./wordpress --file Dockerfile --tag liveperson_wp:${{ steps.date.outputs.date }}
      
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
