name: Docker Image CI for dev env
 
on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ dev ]
 
jobs:
  login-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: check user password
      run: echo  "${{ secrets.DOCKERHUB_USERNAME }} is username and password is ${{ secrets.DOCKERHUB_TOKEN }}"
 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: '${{ secrets.DOCKERHUB_USERNAME }}'
        password: '${{ secrets.DOCKERHUB_TOKEN }}'
        
    - name: Check out code
      uses: actions/checkout@v2

    - name: Get current date 
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    
    - name: Build  the Docker image
      run:   docker build . --file Dockerfile --tag  ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ steps.date.outputs.date }}
      
    - name: Docker Push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ steps.date.outputs.date }}
 