name: Docker Image CI for dev env
 
on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ dev ]
 
jobs:
  login-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: check user password
      run: echo  "${{ secrets.DOCKERHUB_USERNAME }} is username and password is ${{ secrets.DOCKERHUB_TOKEN }}"
 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: '${{ secrets.DOCKERHUB_USERNAME }}'
        password: '${{ secrets.DOCKERHUB_TOKEN }}'
        
    - name: Check out code and build
      uses: actions/checkout@v2
      with:
        push: true
        tags: user/app:latest
        
    - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:mysubdir"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
  